# Generated by Django 4.0.4 on 2022-06-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigup_app', '0003_rename_profile_pic_profile_avatar_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
